# fly -t ci sp -p ruby-cf-sample-app -c pipeline.yml -l pipeline-secrets.yml
---
jobs:
- name: deploy
  plan:
  - get: source-code
    trigger: true
  - put: cloud-foundry
    params:
      commands:
      - command: create-org
      - command: create-space
      - command: push
        path: source-code
        manifest: source-code/manifest.yml

resources:
- name: source-code
  type: git
  source:
    uri: ((source_code.uri))
    branch: ((source_code.branch))
    private_key: ((git_key.private_key))

- name: cloud-foundry
  type: cf-cli-resource
  source:
    api: ((cf.api))
    username: ((cf.username))
    password: ((cf.password))
    org: ((cf.org))
    space: ((cf.space))

resource_types:
- name: cf-cli-resource
  type: docker-image
  source:
    repository: nulldriver/cf-cli-resource
    tag: latest
